# Generated by Django 4.2.8 on 2024-02-08 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_schedule_app', '0003_lesson_grade_lesson_student_alter_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_obj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='school_schedule_app.class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='day',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_schedule_app.subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='school_schedule_app.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='time',
            field=models.CharField(default=8000, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='class_obj',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_schedule_app.class'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='school_schedule_app.student'),
            preserve_default=False,
        ),
    ]
