# Generated by Django 4.2.8 on 2024-02-09 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_schedule_app', '0005_alter_class_class_obj_alter_class_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_schedule_app.class'),
        ),
    ]
